Add docker
Eleonora-Y/java-shareit pull request #11
Opened 2023-06-11 16:13 UTC by Eleonora-Y

2023-06-12 11:19 UTC, db-exp commented on gateway/pom.xml
> +            <artifactId>spring-webflux</artifactId>
а он тебе зачем) ? это реактивщина, подход хороший, но в рамках курса Java насколько я помню вроде не освещается. Если хочешь - используй

2023-06-12 12:18 UTC, db-exp requested changes

2023-06-12 12:18 UTC, db-exp commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
лучше тут использовать переменную из docker-compose через ${Имя переменной}

2023-06-12 12:18 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> -@Repository
не, верни, пожалуйста

2023-06-12 12:18 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> -    @Transactional(readOnly = true)
тут правильно readOnly

2023-06-12 12:18 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> -    @Transactional(readOnly = true)
тут правильно readOnly

2023-06-12 12:18 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> -    @Transactional(readOnly = true)
тут правильно readOnly

2023-06-12 12:18 UTC, db-exp commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
лучше использовать переменную из docker-compose ${имя переменной}

2023-06-12 12:18 UTC, db-exp commented on gateway/pom.xml
> +            <artifactId>spring-webflux</artifactId>
Не нашел необходимого использования - лучше удалить тогда

2023-06-13 06:00 UTC, db-exp requested changes

2023-06-13 06:00 UTC, db-exp commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://server:9090
вот тут забыла поменять на переменную из docker-compose

2023-06-13 21:06 UTC, db-exp requested changes

2023-06-13 21:06 UTC, db-exp commented on gateway/src/main/resources/application.properties
> +shareit-server.url=SHAREIT_SERVER_URL
https://www.baeldung.com/spring-boot-properties-env-variables

нужно через ${SHAREIT_SERVER_URL}

2023-06-13 21:20 UTC, Eleonora-Y commented on gateway/src/main/resources/application.properties
> +shareit-server.url=SHAREIT_SERVER_URL
я так и собиралась, поспешила и не заметила))

2023-06-13 21:43 UTC, db-exp approved these changes

2023-06-14 08:58 UTC, merged